---
- name: copy dccp script
  vars:
    application: dccp
  template:
    src: blacklist.j2
    dest: /tmp/dccp.sh
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.1
      - dccp  
      
- name: "AUTOMATED | 3.4.1 | PATCH | Ensure DCCP is disabled"
  script: /tmp/dccp.sh
  when:
      - ubtu20cis_rule_3_4_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.1
      - dccp

- name: copy sctp script
  vars:
    application: sctp
  template:
    src: blacklist.j2
    dest: /tmp/sctp.sh
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.2
      - sctp
- name: "AUTOMATED | 3.4.2 | PATCH | Ensure SCTP is disabled"
  script: /tmp/sctp.sh
  when:
      - ubtu20cis_rule_3_4_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.2
      - sctp

- name: copy rds script
  vars:
    application: rds
  template:
    src: blacklist.j2
    dest: /tmp/rds.sh
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.3
      - rds
- name: "AUTOMATED | 3.4.3 | PATCH | Ensure RDS is disabled"
  script: /tmp/rds.sh
  when:
      - ubtu20cis_rule_3_4_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.3
      - rds

- name: copy tipc script
  vars:
    application: tipc
  template:
    src: blacklist.j2
    dest: /tmp/tipc.sh
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.4
      - tipc
- name: "AUTOMATED | 3.4.4 | PATCH | Ensure TIPC is disabled"
  script: /tmp/tipc.sh
  when:
      - ubtu20cis_rule_3_4_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.4
      - tipc
